export enum TagEnum {
  Acao = 'Ação',
  Aventura = 'Aventura',
  CinemaDeArte = 'Cinema de arte',
  Chanchada = 'Chanchada',
  Comedia = 'Comédia',
  ComediaDeAcao = 'Comedia de Ação',
  ComediaDeTerror = 'Comédia de terror',
  ComediaDramatica = 'Comedia Dramatica',
  ComediaRomantica = 'Comedia Romantica', 
  Danca = 'Dança',
  Documentario = 'Documentário',
  Docuficcao = 'Docuficção',
  Drama = 'Drama',
  Espionagem = 'Espionagem',
  Faroeste = 'Faroeste',
  Fantasia = 'Fantasia',
  FantasiaCientifica = 'Fantasia científica',
  FiccaoCientifica = 'Ficção científica',
  FilmesComTruques = 'Filmes com truques',
  FilmesDeGuerra = 'Filmes de guerra',
  Misterio = 'Mistério',
  Musical = 'Musical',
  FilmePolicial = 'Filme Policial',
  Romance = 'Romance',
  Terror = 'Terror',
  Thriller = 'Thriller',
}